<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Comments_m extends MY_Model {

    protected $_table_name = 'comments';
    protected $_primary_key = 'comment_id';
    protected $_primary_filter = 'intval';
    protected $_order_by = "comment_id asc";

    public  function __construct() {
        parent::__construct();
    }
    public function get_comments() {

        $this->db->select('*');
        $this->db->from('comments');
        $this->db->join('contents', 'comments.content_id = contents.content_id','inner');
        $this->db->join('users', 'comment_user_id = user_id','inner');
        $query = $this->db->get();
        return $query->result();
    }
    public function delete($comment_id)
    {
        $this -> db -> where('comment_id', $comment_id);
        $this -> db -> delete('comments');
    }
    function delete_content($arr)
    {
        $this->db->delete('comments', $arr);
    }
    public function insert($array)
    {
        return parent::insert($array); // TODO: Change the autogenerated stub
    }
    public function get_where_comments($arr){

        $this->db->select('comments.content_id,contents.content_title');
        $this->db->from('comments');
        $this->db->where($arr);
        $this->db->join('contents', 'comments.content_id = contents.content_id','inner');
        $this->db->join('users', 'comment_user_id = user_id','inner');
        $this->db->distinct();
        $query = $this->db->get();
        return $query->result();
    }
    public function get_where_full_comments($arr){

        $this->db->select('*');
        $this->db->from('comments');
        $this->db->where($arr);
        $this->db->join('contents', 'comments.content_id = contents.content_id','inner');
        $this->db->join('users', 'comment_user_id = user_id','inner');
        $this->db->distinct();
        $query = $this->db->get();
        return $query->result();
    }
}

?>