<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Coursepermissions_m extends MY_Model {

    protected $_table_name = 'course_permissions';
    protected $_primary_key = 'cs_permission_id';
    protected $_primary_filter = 'intval';
    protected $_order_by = "cs_permission_id asc";

    public  function __construct() {
        parent::__construct();
    }
    public function get_where($arr=null) {

        return parent::get_where($arr);
    }
    public function delete($permissionID)
    {
        return parent::delete($permissionID);
    }

    public function delete_where($array = NULL)
    {
        return parent::delete_where($array); // TODO: Change the autogenerated stub
    }

    public function insert($array)
    {
        return parent::insert($array); // TODO: Change the autogenerated stub
    }
}

?>