<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Schooltypes_m extends MY_Model
{


    protected $_table_name = 'school_types';
    protected $_primary_key = 'school_type_id';
    protected $_primary_filter = 'intval';
    protected $_order_by = "school_type_id asc";

    function __construct()
    {
        parent::__construct();
    }

    public function getItems($arr = array())
    {
        $this->db->select('*')->from('school_types');
        if ($arr) $this->db->where($arr);
        $query = $this->db->get();
        return $query->result();
    }

    public function get_school_types($arr = array())
    {
        $this->db->select('*')->from('school_types');
        $query = $this->db->get();
        return $query->result();
    }

    public function get_all_school_types()
    {
        $this->db->select('*')->from('school_types');
        $query = $this->db->get();
        return $query->result();
    }

    public function get($id, $single = FALSE)
    {
        return parent::get($id, $single); // TODO: Change the autogenerated stub
    }

    public function get_where($array = NULL)
    {
        return parent::get_where($array); // TODO: Change the autogenerated stub
    }

    public function delete($school_type_id)
    {
        $this->db->where('school_type_id', $school_type_id);
        $this->db->delete('school_types');
        return $this->get_all_school_types();
    }
}
