<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Subwaretypes_m extends MY_Model {


    protected $_table_name = 'subware_types';
    protected $_primary_key = 'subware_type_id';
    protected $_primary_filter = 'intval';
    protected $_order_by = "subware_type_id asc";

    function __construct() {
        parent::__construct();
    }
    public function get_swtypes()
    {
         $this->db->select('*')->from('subware_types');
        $query = $this->db->get();
        return $query->result();
    }
    public function get_all_swtypes()
    {
        $this->db->select('*')->from('subware_types');
        $query = $this->db->get();
        return $query->result();
    }

    public function get($id, $single = FALSE)
    {
        return parent::get($id, $single); // TODO: Change the autogenerated stub
    }
    public function get_where($array = NULL)
    {
        return parent::get_where($array); // TODO: Change the autogenerated stub
    }

}
